/**
 * JSDoc Type Definitions and Constants for ORION Adaptive Model Routing
 */

const TASK_TYPES = {
  TEXT_QA: "TEXT_QA",
  DOCUMENT_SUMMARY: "DOCUMENT_SUMMARY",
  DOCUMENT_EXTRACTION: "DOCUMENT_EXTRACTION",
  MULTIMODAL_ANALYSIS: "MULTIMODAL_ANALYSIS",
  CODE_GENERATION: "CODE_GENERATION",
  CODE_REVIEW: "CODE_REVIEW",
  DATA_ANALYSIS: "DATA_ANALYSIS",
  CALCULATION: "CALCULATION",
  REPORT_GENERATION: "REPORT_GENERATION",
  GENERAL_REASONING: "GENERAL_REASONING",
};

const TASK_COMPLEXITIES = {
  LOW: "LOW",
  MEDIUM: "MEDIUM",
  HIGH: "HIGH",
};

const SENSITIVITY_LEVELS = {
  PUBLIC: 0,
  INTERNAL: 1,
  CONFIDENTIAL: 2,
  RESTRICTED: 3,
};

const SENSITIVITY_ORDER = ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"];

const TRUST_STATUS = {
  APPROVED: "approved",
  DISABLED: "disabled",
  TESTING: "testing",
};

const ROUTING_STATUS = {
  SELECTED: "SELECTED",
  NO_ELIGIBLE_MODEL: "NO_ELIGIBLE_MODEL",
};

module.exports = {
  TASK_TYPES,
  TASK_COMPLEXITIES,
  SENSITIVITY_LEVELS,
  SENSITIVITY_ORDER,
  TRUST_STATUS,
  ROUTING_STATUS,
};
