import React, { useEffect, useState } from "react";
import Sidebar, { SidebarMobileHeader } from "@/components/Sidebar";
import { isMobile } from "react-device-detect";
import {
  Package,
  DownloadSimple,
  FileDoc,
  FileXls,
  FilePdf,
  FileCode,
  FileText,
  CircleNotch,
  MagnifyingGlass,
  ArrowSquareOut,
  Calendar,
  HardDrive,
  Presentation,
  FolderOpen,
} from "@phosphor-icons/react";
import Deliverables from "@/models/deliverables";
import showToast from "@/utils/toast";
import { humanFileSize } from "@/utils/numbers";
import { saveAs } from "file-saver";

export default function DeliverablesPage() {
  const [deliverables, setDeliverables] = useState([]);
  const [loading, setLoading] = useState(true);
  const [selectedFilter, setSelectedFilter] = useState("all");
  const [searchQuery, setSearchQuery] = useState("");
  const [downloadingId, setDownloadingId] = useState(null);

  useEffect(() => {
    loadDeliverables();
  }, []);

  async function loadDeliverables() {
    setLoading(true);
    try {
      const items = await Deliverables.all();
      setDeliverables(items || []);
    } catch (err) {
      console.error("Failed to load deliverables:", err);
      showToast("Could not load deliverables", "error");
    } finally {
      setLoading(false);
    }
  }

  async function handleDownload(item) {
    setDownloadingId(item.id);
    try {
      const res = await fetch(item.downloadUrl);
      if (!res.ok) throw new Error("Download failed");
      const blob = await res.blob();
      saveAs(blob, item.filename);
      showToast(`Downloaded ${item.filename}`, "success");
    } catch (err) {
      console.error("Download error:", err);
      showToast("Failed to download artifact", "error");
    } finally {
      setDownloadingId(null);
    }
  }

  const filteredItems = deliverables.filter((item) => {
    const matchesType =
      selectedFilter === "all"
        ? true
        : selectedFilter === "docx"
        ? ["docx", "doc"].includes(item.extension)
        : selectedFilter === "xlsx"
        ? ["xlsx", "xls", "csv"].includes(item.extension)
        : selectedFilter === "pptx"
        ? ["pptx", "ppt"].includes(item.extension)
        : selectedFilter === "pdf"
        ? item.extension === "pdf"
        : selectedFilter === "code"
        ? ["js", "py", "ts", "json", "sh", "html", "css"].includes(item.extension)
        : true;

    const matchesSearch =
      (item.title || item.filename || "").toLowerCase().includes(searchQuery.toLowerCase());

    return matchesType && matchesSearch;
  });

  function getDeliverableIcon(ext = "") {
    if (["docx", "doc"].includes(ext))
      return <FileDoc size={24} className="text-sky-400" weight="duotone" />;
    if (["xlsx", "xls", "csv"].includes(ext))
      return <FileXls size={24} className="text-emerald-400" weight="duotone" />;
    if (["pptx", "ppt"].includes(ext))
      return <Presentation size={24} className="text-amber-400" weight="duotone" />;
    if (ext === "pdf")
      return <FilePdf size={24} className="text-rose-400" weight="duotone" />;
    if (["js", "py", "ts", "json", "sh"].includes(ext))
      return <FileCode size={24} className="text-sky-400" weight="duotone" />;
    return <FileText size={24} className="text-zinc-400" weight="duotone" />;
  }

  return (
    <div className="w-screen h-screen overflow-hidden bg-[#090a0b] text-[#f4f4f5] flex font-sans">
      {!isMobile ? <Sidebar /> : <SidebarMobileHeader />}

      <main className="flex-1 h-full overflow-y-auto bg-[#090a0b] p-6 md:p-10 pt-16 md:pt-10">
        <div className="max-w-6xl mx-auto space-y-8 pb-16">
          {/* Header */}
          <div className="flex flex-col md:flex-row md:items-center justify-between gap-4 border-b border-[#1f2328] pb-6">
            <div>
              <div className="flex items-center gap-2 mb-2">
                <span className="sovereign-badge sovereign-badge-sky font-mono">
                  GENERATED ARTIFACTS REGISTRY
                </span>
                <span className="text-xs text-zinc-500 font-mono">Local Storage Delivery</span>
              </div>
              <h1 className="text-2xl md:text-3xl font-extrabold text-white tracking-tight">
                Deliverables &amp; Output Hub
              </h1>
              <p className="text-sm text-zinc-400 mt-1">
                Centralized registry for all reports, spreadsheets, slide presentations, and code artifacts generated by Sovereign AI agents.
              </p>
            </div>
          </div>

          {/* Filters and Search Bar */}
          <div className="flex flex-col sm:flex-row items-center justify-between gap-4">
            <div className="flex items-center gap-1.5 p-1 rounded-xl bg-[#111215] border border-[#1f2328] text-xs font-mono overflow-x-auto w-full sm:w-auto">
              {[
                { id: "all", label: "All Formats" },
                { id: "docx", label: "Word (.docx)" },
                { id: "xlsx", label: "Excel (.xlsx)" },
                { id: "pptx", label: "PowerPoint (.pptx)" },
                { id: "pdf", label: "PDF" },
                { id: "code", label: "Code" },
              ].map((filter) => (
                <button
                  key={filter.id}
                  onClick={() => setSelectedFilter(filter.id)}
                  className={`px-3 py-1.5 rounded-lg font-bold transition-all whitespace-nowrap ${
                    selectedFilter === filter.id
                      ? "bg-sky-500 text-zinc-950 shadow-sm"
                      : "text-zinc-400 hover:text-white"
                  }`}
                >
                  {filter.label}
                </button>
              ))}
            </div>

            <div className="relative w-full sm:w-72">
              <MagnifyingGlass size={16} className="absolute left-3.5 top-3.5 text-zinc-500" />
              <input
                type="text"
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                placeholder="Search deliverables..."
                className="w-full pl-10 pr-4 py-2 rounded-xl bg-[#111215] border border-[#1f2328] text-xs text-zinc-200 placeholder-zinc-500 focus:outline-none focus:border-sky-500 transition-colors"
              />
            </div>
          </div>

          {/* Deliverables Grid */}
          {loading ? (
            <div className="py-20 text-center text-zinc-500 flex flex-col items-center gap-3">
              <CircleNotch size={28} className="animate-spin text-sky-400" />
              <span className="text-xs font-mono">Loading local artifacts registry...</span>
            </div>
          ) : filteredItems.length === 0 ? (
            <div className="sovereign-card rounded-2xl p-16 text-center space-y-4">
              <FolderOpen size={48} className="mx-auto text-zinc-600" weight="duotone" />
              <div className="text-sm font-bold text-zinc-200">No deliverables generated yet</div>
              <p className="text-xs text-zinc-400 max-w-md mx-auto leading-relaxed">
                When agents generate reports, spreadsheets, slide presentations, or code outputs during chat sessions, they are stored locally and indexed here for instant download.
              </p>
            </div>
          ) : (
            <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-4">
              {filteredItems.map((item) => (
                <div
                  key={item.id}
                  className="sovereign-card rounded-2xl p-5 space-y-4 flex flex-col justify-between group"
                >
                  <div className="space-y-3">
                    <div className="flex items-start justify-between gap-3">
                      <div className="p-3 rounded-xl bg-[#090a0b] border border-[#1f2328]">
                        {getDeliverableIcon(item.extension)}
                      </div>
                      <span className="sovereign-badge sovereign-badge-sky font-mono uppercase">
                        .{item.extension}
                      </span>
                    </div>

                    <div>
                      <h3 className="text-sm font-bold text-white group-hover:text-sky-400 transition-colors line-clamp-1">
                        {item.title || item.filename}
                      </h3>
                      <p className="text-xs text-zinc-400 mt-1 line-clamp-2 leading-relaxed">
                        {item.description || "Generated confidential artifact."}
                      </p>
                    </div>
                  </div>

                  <div className="pt-3 border-t border-[#1f2328] flex items-center justify-between text-xs text-zinc-400">
                    <span className="font-mono">{humanFileSize(item.size || 20480)}</span>
                    <button
                      onClick={() => handleDownload(item)}
                      disabled={downloadingId === item.id}
                      className="inline-flex items-center gap-1.5 px-3 py-1.5 rounded-lg bg-sky-500/10 hover:bg-sky-500/20 text-sky-400 border border-sky-500/30 text-xs font-bold transition-all active:scale-95"
                    >
                      {downloadingId === item.id ? (
                        <CircleNotch size={14} className="animate-spin" />
                      ) : (
                        <DownloadSimple size={14} weight="bold" />
                      )}
                      <span>Download</span>
                    </button>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </main>
    </div>
  );
}
