const WATCH_DIRECTORY = require("path").resolve(__dirname, "../hotdir");

const ACCEPTED_MIMES = {
  "text/plain": [
    ".txt",
    ".md",
    ".markdown",
    ".mdown",
    ".mdx",
    ".org",
    ".adoc",
    ".asciidoc",
    ".rst",
    ".tex",
    ".latex",
    ".rtf",
    ".log",
    ".text",
    ".py",
    ".pyw",
    ".js",
    ".jsx",
    ".ts",
    ".tsx",
    ".mjs",
    ".cjs",
    ".c",
    ".cpp",
    ".cc",
    ".cxx",
    ".h",
    ".hpp",
    ".cs",
    ".java",
    ".go",
    ".rs",
    ".rb",
    ".php",
    ".swift",
    ".kt",
    ".kts",
    ".dart",
    ".r",
    ".lua",
    ".pl",
    ".pm",
    ".scala",
    ".groovy",
    ".zig",
    ".nim",
    ".v",
    ".vue",
    ".svelte",
    ".proto",
    ".graphql",
    ".gql",
    ".sql",
    ".sh",
    ".bash",
    ".zsh",
    ".fish",
    ".ps1",
    ".bat",
    ".cmd",
    ".yaml",
    ".yml",
    ".xml",
    ".toml",
    ".ini",
    ".cfg",
    ".conf",
    ".env",
    ".properties",
    ".diff",
    ".patch",
    ".vtt",
    ".srt",
  ],
  "text/html": [".html", ".htm", ".xhtml"],
  "text/csv": [".csv", ".tsv", ".tab"],
  "application/json": [".json", ".jsonl"],
  "application/msword": [".doc"],
  "application/vnd.openxmlformats-officedocument.wordprocessingml.document": [
    ".docx",
  ],
  "application/vnd.openxmlformats-officedocument.presentationml.presentation": [
    ".pptx",
  ],
  "application/vnd.ms-powerpoint": [".ppt"],
  "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet": [
    ".xlsx",
  ],
  "application/vnd.ms-excel": [".xls"],
  "application/vnd.oasis.opendocument.text": [".odt"],
  "application/vnd.oasis.opendocument.presentation": [".odp"],
  "application/vnd.oasis.opendocument.spreadsheet": [".ods"],

  "application/pdf": [".pdf"],
  "application/mbox": [".mbox"],

  "audio/wav": [".wav"],
  "audio/mpeg": [".mp3"],
  "audio/ogg": [".ogg", ".oga"],
  "audio/opus": [".opus"],
  "audio/mp4": [".m4a"],
  "audio/x-m4a": [".m4a"],
  "audio/webm": [".webm"],
  "audio/flac": [".flac"],
  "audio/aac": [".aac"],

  "video/mp4": [".mp4"],
  "video/mpeg": [".mpeg"],
  "video/webm": [".webm"],
  "application/epub+zip": [".epub"],
  "image/png": [".png"],
  "image/jpeg": [".jpg", ".jpeg"],
  "image/webp": [".webp"],
  "image/bmp": [".bmp"],
  "image/tiff": [".tiff", ".tif"],
};

const SUPPORTED_FILETYPE_CONVERTERS = {
  // Plain text and Markdown documentation
  ".txt": "./convert/asTxt.js",
  ".text": "./convert/asTxt.js",
  ".md": "./convert/asTxt.js",
  ".markdown": "./convert/asTxt.js",
  ".mdown": "./convert/asTxt.js",
  ".mdx": "./convert/asTxt.js",
  ".org": "./convert/asTxt.js",
  ".adoc": "./convert/asTxt.js",
  ".asciidoc": "./convert/asTxt.js",
  ".rst": "./convert/asTxt.js",
  ".tex": "./convert/asTxt.js",
  ".latex": "./convert/asTxt.js",
  ".rtf": "./convert/asTxt.js",
  ".log": "./convert/asTxt.js",

  // Tabular and structured data
  ".csv": "./convert/asTxt.js",
  ".tsv": "./convert/asTxt.js",
  ".tab": "./convert/asTxt.js",
  ".json": "./convert/asTxt.js",
  ".jsonl": "./convert/asTxt.js",
  ".html": "./convert/asTxt.js",
  ".htm": "./convert/asTxt.js",
  ".xhtml": "./convert/asTxt.js",
  ".xml": "./convert/asTxt.js",
  ".yaml": "./convert/asTxt.js",
  ".yml": "./convert/asTxt.js",
  ".toml": "./convert/asTxt.js",
  ".ini": "./convert/asTxt.js",
  ".cfg": "./convert/asTxt.js",
  ".conf": "./convert/asTxt.js",
  ".env": "./convert/asTxt.js",
  ".properties": "./convert/asTxt.js",
  ".diff": "./convert/asTxt.js",
  ".patch": "./convert/asTxt.js",
  ".vtt": "./convert/asTxt.js",
  ".srt": "./convert/asTxt.js",

  // Source code languages
  ".py": "./convert/asTxt.js",
  ".pyw": "./convert/asTxt.js",
  ".js": "./convert/asTxt.js",
  ".jsx": "./convert/asTxt.js",
  ".ts": "./convert/asTxt.js",
  ".tsx": "./convert/asTxt.js",
  ".mjs": "./convert/asTxt.js",
  ".cjs": "./convert/asTxt.js",
  ".c": "./convert/asTxt.js",
  ".cpp": "./convert/asTxt.js",
  ".cc": "./convert/asTxt.js",
  ".cxx": "./convert/asTxt.js",
  ".h": "./convert/asTxt.js",
  ".hpp": "./convert/asTxt.js",
  ".cs": "./convert/asTxt.js",
  ".java": "./convert/asTxt.js",
  ".go": "./convert/asTxt.js",
  ".rs": "./convert/asTxt.js",
  ".rb": "./convert/asTxt.js",
  ".php": "./convert/asTxt.js",
  ".swift": "./convert/asTxt.js",
  ".kt": "./convert/asTxt.js",
  ".kts": "./convert/asTxt.js",
  ".dart": "./convert/asTxt.js",
  ".r": "./convert/asTxt.js",
  ".lua": "./convert/asTxt.js",
  ".pl": "./convert/asTxt.js",
  ".pm": "./convert/asTxt.js",
  ".scala": "./convert/asTxt.js",
  ".groovy": "./convert/asTxt.js",
  ".zig": "./convert/asTxt.js",
  ".nim": "./convert/asTxt.js",
  ".v": "./convert/asTxt.js",
  ".vue": "./convert/asTxt.js",
  ".svelte": "./convert/asTxt.js",
  ".proto": "./convert/asTxt.js",
  ".graphql": "./convert/asTxt.js",
  ".gql": "./convert/asTxt.js",
  ".sql": "./convert/asTxt.js",
  ".sh": "./convert/asTxt.js",
  ".bash": "./convert/asTxt.js",
  ".zsh": "./convert/asTxt.js",
  ".fish": "./convert/asTxt.js",
  ".ps1": "./convert/asTxt.js",
  ".bat": "./convert/asTxt.js",
  ".cmd": "./convert/asTxt.js",
  ".css": "./convert/asTxt.js",
  ".scss": "./convert/asTxt.js",
  ".sass": "./convert/asTxt.js",
  ".less": "./convert/asTxt.js",

  // PDF
  ".pdf": "./convert/asPDF/index.js",

  // Microsoft Word documents
  ".docx": "./convert/asDocx.js",
  ".doc": "./convert/asDoc.js",

  // Presentations and Office Open Mimes
  ".pptx": "./convert/asOfficeMime.js",
  ".ppt": "./convert/asOfficeMime.js",
  ".odt": "./convert/asOfficeMime.js",
  ".odp": "./convert/asOfficeMime.js",
  ".ods": "./convert/asOfficeMime.js",

  // Spreadsheets
  ".xlsx": "./convert/asXlsx.js",
  ".xls": "./convert/asXlsx.js",

  // Email and E-books
  ".mbox": "./convert/asMbox.js",
  ".epub": "./convert/asEPub.js",

  // Audio and Video
  ".mp3": "./convert/asAudio.js",
  ".wav": "./convert/asAudio.js",
  ".mp4": "./convert/asAudio.js",
  ".mpeg": "./convert/asAudio.js",
  ".ogg": "./convert/asAudio.js",
  ".oga": "./convert/asAudio.js",
  ".opus": "./convert/asAudio.js",
  ".m4a": "./convert/asAudio.js",
  ".webm": "./convert/asAudio.js",
  ".flac": "./convert/asAudio.js",
  ".aac": "./convert/asAudio.js",

  // Images
  ".png": "./convert/asImage.js",
  ".jpg": "./convert/asImage.js",
  ".jpeg": "./convert/asImage.js",
  ".webp": "./convert/asImage.js",
  ".bmp": "./convert/asImage.js",
  ".tiff": "./convert/asImage.js",
  ".tif": "./convert/asImage.js",
};

module.exports = {
  SUPPORTED_FILETYPE_CONVERTERS,
  WATCH_DIRECTORY,
  ACCEPTED_MIMES,
};
