const { TASK_TYPES, TRUST_STATUS } = require("../contracts/types");

/**
 * Default local model registry for ORION Adaptive Model Routing.
 * Represents local model categories defined in ORION PPT architecture:
 * Reasoning, Vision, Code, General, and Domain-Specific models.
 */
const DEFAULT_MODEL_PROFILES = [
  // ─── 1. REASONING MODELS ───────────────────────────────────────────────────
  {
    id: "deepseek-r1:14b",
    displayName: "DeepSeek R1 Distill 14B (Reasoning)",
    runtime: "ollama",
    provider: "ollama",
    model: "deepseek-r1:14b",
    category: "reasoning",
    capabilities: {
      text: true,
      vision: false,
      code: true,
      toolUse: true,
      reasoning: true,
      longContext: true,
    },
    contextLength: 65536,
    resourceRequirements: {
      minRamGb: 16,
      minVramGb: 10,
      recommendedVramGb: 12,
    },
    sensitivityAccess: ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"],
    allowedRoles: ["default", "admin", "manager"],
    trustStatus: TRUST_STATUS.APPROVED,
    enabled: true,
    priority: 95,
    taskAffinity: {
      [TASK_TYPES.GENERAL_REASONING]: 1.0,
      [TASK_TYPES.CALCULATION]: 0.95,
      [TASK_TYPES.DATA_ANALYSIS]: 0.9,
      [TASK_TYPES.REPORT_GENERATION]: 0.9,
      [TASK_TYPES.DOCUMENT_SUMMARY]: 0.85,
      [TASK_TYPES.TEXT_QA]: 0.8,
      [TASK_TYPES.CODE_REVIEW]: 0.85,
    },
  },
  {
    id: "deepseek-r1:8b",
    displayName: "DeepSeek R1 Distill 8B (Compact Reasoning)",
    runtime: "ollama",
    provider: "ollama",
    model: "deepseek-r1:8b",
    category: "reasoning",
    capabilities: {
      text: true,
      vision: false,
      code: true,
      toolUse: true,
      reasoning: true,
      longContext: false,
    },
    contextLength: 32768,
    resourceRequirements: {
      minRamGb: 8,
      minVramGb: 6,
      recommendedVramGb: 8,
    },
    sensitivityAccess: ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"],
    allowedRoles: ["default", "admin", "manager"],
    trustStatus: TRUST_STATUS.APPROVED,
    enabled: true,
    priority: 88,
    taskAffinity: {
      [TASK_TYPES.GENERAL_REASONING]: 0.9,
      [TASK_TYPES.CALCULATION]: 0.85,
      [TASK_TYPES.TEXT_QA]: 0.8,
      [TASK_TYPES.DOCUMENT_SUMMARY]: 0.8,
    },
  },

  // ─── 2. VISION MODELS ──────────────────────────────────────────────────────
  {
    id: "qwen2-vl:7b",
    displayName: "Qwen2-VL 7B (Vision & OCR)",
    runtime: "ollama",
    provider: "ollama",
    model: "qwen2-vl:7b",
    category: "vision",
    capabilities: {
      text: true,
      vision: true,
      code: false,
      toolUse: true,
      reasoning: false,
      longContext: true,
    },
    contextLength: 32768,
    resourceRequirements: {
      minRamGb: 8,
      minVramGb: 6,
      recommendedVramGb: 8,
    },
    sensitivityAccess: ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"],
    allowedRoles: ["default", "admin", "manager"],
    trustStatus: TRUST_STATUS.APPROVED,
    enabled: true,
    priority: 95,
    taskAffinity: {
      [TASK_TYPES.MULTIMODAL_ANALYSIS]: 1.0,
      [TASK_TYPES.DOCUMENT_EXTRACTION]: 0.9,
      [TASK_TYPES.DOCUMENT_SUMMARY]: 0.75,
      [TASK_TYPES.TEXT_QA]: 0.7,
    },
  },
  {
    id: "llama3.2-vision:11b",
    displayName: "Llama 3.2 11B Vision",
    runtime: "ollama",
    provider: "ollama",
    model: "llama3.2-vision:11b",
    category: "vision",
    capabilities: {
      text: true,
      vision: true,
      code: false,
      toolUse: true,
      reasoning: false,
      longContext: true,
    },
    contextLength: 65536,
    resourceRequirements: {
      minRamGb: 20,
      minVramGb: 9,
      recommendedVramGb: 12,
    },
    sensitivityAccess: ["PUBLIC", "INTERNAL", "CONFIDENTIAL"],
    allowedRoles: ["default", "admin", "manager"],
    trustStatus: TRUST_STATUS.APPROVED,
    enabled: true,
    priority: 90,
    taskAffinity: {
      [TASK_TYPES.MULTIMODAL_ANALYSIS]: 0.95,
      [TASK_TYPES.DOCUMENT_EXTRACTION]: 0.85,
    },
  },

  // ─── 3. CODE MODELS ────────────────────────────────────────────────────────
  {
    id: "qwen2.5-coder:14b",
    displayName: "Qwen 2.5 Coder 14B",
    runtime: "ollama",
    provider: "ollama",
    model: "qwen2.5-coder:14b",
    category: "code",
    capabilities: {
      text: true,
      vision: false,
      code: true,
      toolUse: true,
      reasoning: true,
      longContext: true,
    },
    contextLength: 65536,
    resourceRequirements: {
      minRamGb: 16,
      minVramGb: 10,
      recommendedVramGb: 12,
    },
    sensitivityAccess: ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"],
    allowedRoles: ["default", "admin", "manager"],
    trustStatus: TRUST_STATUS.APPROVED,
    enabled: true,
    priority: 95,
    taskAffinity: {
      [TASK_TYPES.CODE_GENERATION]: 1.0,
      [TASK_TYPES.CODE_REVIEW]: 1.0,
      [TASK_TYPES.DOCUMENT_EXTRACTION]: 0.8,
      [TASK_TYPES.TEXT_QA]: 0.7,
    },
  },
  {
    id: "qwen2.5-coder:7b",
    displayName: "Qwen 2.5 Coder 7B",
    runtime: "ollama",
    provider: "ollama",
    model: "qwen2.5-coder:7b",
    category: "code",
    capabilities: {
      text: true,
      vision: false,
      code: true,
      toolUse: true,
      reasoning: false,
      longContext: true,
    },
    contextLength: 32768,
    resourceRequirements: {
      minRamGb: 8,
      minVramGb: 5,
      recommendedVramGb: 6,
    },
    sensitivityAccess: ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"],
    allowedRoles: ["default", "admin", "manager"],
    trustStatus: TRUST_STATUS.APPROVED,
    enabled: true,
    priority: 90,
    taskAffinity: {
      [TASK_TYPES.CODE_GENERATION]: 0.95,
      [TASK_TYPES.CODE_REVIEW]: 0.9,
    },
  },

  // ─── 4. GENERAL / WORKSPACE QA & SUMMARY MODELS ───────────────────────────
  {
    id: "llama3.1:8b",
    displayName: "Llama 3.1 8B Instruct",
    runtime: "ollama",
    provider: "ollama",
    model: "llama3.1:8b",
    category: "general",
    capabilities: {
      text: true,
      vision: false,
      code: true,
      toolUse: true,
      reasoning: false,
      longContext: true,
    },
    contextLength: 131072,
    resourceRequirements: {
      minRamGb: 8,
      minVramGb: 6,
      recommendedVramGb: 8,
    },
    sensitivityAccess: ["PUBLIC", "INTERNAL", "CONFIDENTIAL", "RESTRICTED"],
    allowedRoles: ["default", "admin", "manager"],
    trustStatus: TRUST_STATUS.APPROVED,
    enabled: true,
    priority: 85,
    taskAffinity: {
      [TASK_TYPES.TEXT_QA]: 1.0,
      [TASK_TYPES.DOCUMENT_SUMMARY]: 1.0,
      [TASK_TYPES.DOCUMENT_EXTRACTION]: 0.9,
      [TASK_TYPES.REPORT_GENERATION]: 0.85,
    },
  },
  {
    id: "mistral:7b",
    displayName: "Mistral 7B Instruct v0.3",
    runtime: "ollama",
    provider: "ollama",
    model: "mistral:7b",
    category: "general",
    capabilities: {
      text: true,
      vision: false,
      code: false,
      toolUse: true,
      reasoning: false,
      longContext: false,
    },
    contextLength: 32768,
    resourceRequirements: {
      minRamGb: 8,
      minVramGb: 5,
      recommendedVramGb: 6,
    },
    sensitivityAccess: ["PUBLIC", "INTERNAL", "CONFIDENTIAL"],
    allowedRoles: ["default", "admin", "manager"],
    trustStatus: TRUST_STATUS.APPROVED,
    enabled: true,
    priority: 75,
    taskAffinity: {
      [TASK_TYPES.TEXT_QA]: 0.9,
      [TASK_TYPES.DOCUMENT_SUMMARY]: 0.9,
    },
  },

  // ─── 5. DOMAIN-SPECIFIC MODELS ─────────────────────────────────────────────
  {
    id: "saullm:7b",
    displayName: "SaulLM 7B Legal Expert",
    runtime: "ollama",
    provider: "ollama",
    model: "saullm:7b",
    category: "domain-specific",
    capabilities: {
      text: true,
      vision: false,
      code: false,
      toolUse: false,
      reasoning: true,
      longContext: true,
    },
    contextLength: 32768,
    resourceRequirements: {
      minRamGb: 12,
      minVramGb: 5,
      recommendedVramGb: 6,
    },
    sensitivityAccess: ["CONFIDENTIAL", "RESTRICTED"],
    allowedRoles: ["admin", "manager"],
    trustStatus: TRUST_STATUS.APPROVED,
    enabled: true,
    priority: 90,
    taskAffinity: {
      [TASK_TYPES.REPORT_GENERATION]: 0.95,
      [TASK_TYPES.DOCUMENT_SUMMARY]: 0.9,
      [TASK_TYPES.TEXT_QA]: 0.85,
    },
  },
];

module.exports = {
  DEFAULT_MODEL_PROFILES,
};
