/**
 * Types, Enums and Constants for Closed-Loop Verification & Self-Repair
 * Sovereign Industrial AI Workbench (SIH PS 26117)
 */

const VerificationStatus = Object.freeze({
  PENDING: "PENDING",
  VERIFYING: "VERIFYING",
  PASSED: "PASSED",
  FAILED: "FAILED",
  UNCERTAIN: "UNCERTAIN",
  REQUIRES_HUMAN_REVIEW: "REQUIRES_HUMAN_REVIEW",
});

const RepairStrategy = Object.freeze({
  SCHEMA_CORRECTION: "SCHEMA_CORRECTION",
  RECALCULATION: "RECALCULATION",
  QUERY_REFINEMENT: "QUERY_REFINEMENT",
  RETRIEVAL_EXPANSION: "RETRIEVAL_EXPANSION",
  MODEL_ESCALATION: "MODEL_ESCALATION",
  PARAMETER_CORRECTION: "PARAMETER_CORRECTION",
  DELIVERABLE_REBUILD: "DELIVERABLE_REBUILD",
});

const StepType = Object.freeze({
  TOOL_CALL: "TOOL_CALL",
  DELIVERABLE: "DELIVERABLE",
  CALCULATION: "CALCULATION",
  STRUCTURED_OUTPUT: "STRUCTURED_OUTPUT",
  RAG_GROUNDING: "RAG_GROUNDING",
  CODE_EXECUTION: "CODE_EXECUTION",
  TEXT_RESPONSE: "TEXT_RESPONSE",
});

const RootCauseCategory = Object.freeze({
  SYNTAX_ERROR: "SYNTAX_ERROR",
  SCHEMA_VIOLATION: "SCHEMA_VIOLATION",
  CALCULATION_DRIFT: "CALCULATION_DRIFT",
  UNGROUNDED_CLAIM: "UNGROUNDED_CLAIM",
  CORRUPT_DELIVERABLE: "CORRUPT_DELIVERABLE",
  TOOL_EXECUTION_FAILURE: "TOOL_EXECUTION_FAILURE",
  UNKNOWN_ANOMALY: "UNKNOWN_ANOMALY",
});

const MAX_REPAIR_ATTEMPTS = 2;

module.exports = {
  VerificationStatus,
  RepairStrategy,
  StepType,
  RootCauseCategory,
  MAX_REPAIR_ATTEMPTS,
};
